// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand. Bump the version in
// package.json and rerun `pnpm build` (or any pretest/prebuild hook); the script reads
// package.json:version and rewrites this file before tsc compiles it.
export const SDK_VERSION = '1.1.3';
