"""
Django settings for todoproject project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import arguslog
from arguslog.integrations.excepthook import install_excepthook
from arguslog.integrations.logging import install_logging_handler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ARGUSLOG_DSN = os.environ.get(
    "ARGUSLOG_DSN",
    # Replace with your project's DSN from the dashboard (Project → Settings → DSN keys).
    # Format: arguslog://<public-key>@<ingest-host>/api/<project-id>
    "arguslog://YOUR_PUBLIC_KEY@localhost:8080/api/0",
)
ARGUSLOG_ENVIRONMENT = os.environ.get("ARGUSLOG_ENV", "development")
ARGUSLOG_RELEASE = os.environ.get("ARGUSLOG_RELEASE", "todo-demo@0.1.0")

_arguslog_client = arguslog.init(
    arguslog.ArguslogOptions(
        dsn=ARGUSLOG_DSN,
        environment=ARGUSLOG_ENVIRONMENT,
        release=ARGUSLOG_RELEASE,
        sample_rate=1.0,
        max_queue_size=512,
        flush_timeout_seconds=3.0,
        scrubbing_enabled=True,
        extra_scrub_patterns=[r"todo_secret_\w+"],
        debug=True,
    )
)
install_excepthook(_arguslog_client)
install_logging_handler(_arguslog_client, level=30)
arguslog.set_tag("component", "django-todo-demo")
arguslog.set_tag("framework", "django")
arguslog.set_context(
    "runtime",
    {"python_sdk": arguslog.SDK_VERSION, "sdk_name": arguslog.SDK_NAME},
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v(gacx^zb0_$_&k-^l5#*my+o)g&!pylzzk%d&lal)y5%3*+gt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'todos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'todos.middleware.ArguslogRequestMiddleware',
]

ROOT_URLCONF = 'todoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
