export type Level = 'fatal' | 'error' | 'warning' | 'info' | 'debug';

export type Platform = 'javascript' | 'node';

export interface User {
  id?: string;
  email?: string;
  username?: string;
}

export interface Breadcrumb {
  timestamp: number;
  category: string;
  message: string;
  level: Level;
  data?: Record<string, unknown>;
}

export interface StackFrame {
  filename?: string;
  function?: string;
  lineno?: number;
  colno?: number;
  inApp?: boolean;
}

export interface ExceptionPayload {
  type: string;
  value: string;
  stacktrace?: { frames: StackFrame[] };
}

export interface EventPayload {
  eventId: string;
  timestamp: number;
  platform: Platform;
  sdk: { name: string; version: string };
  release?: string;
  environment?: string;
  level: Level;
  message?: string;
  exception?: { values: ExceptionPayload[] };
  user?: User;
  tags?: Record<string, string>;
  contexts?: Record<string, Record<string, unknown>>;
  breadcrumbs?: Breadcrumb[];
  request?: { url?: string; userAgent?: string };
}

export type BeforeSend = (
  event: EventPayload,
) => EventPayload | null | Promise<EventPayload | null>;

export interface ArguslogOptions {
  dsn: string;
  release?: string;
  environment?: string;
  sampleRate?: number;
  maxBreadcrumbs?: number;
  beforeSend?: BeforeSend;
  scrubbing?: { enabled?: boolean; extraPatterns?: RegExp[] };
  transport?: { fetch?: typeof fetch; maxRetries?: number };
  integrations?: string[];
  debug?: boolean;
}

export interface ParsedDsn {
  publicKey: string;
  host: string;
  protocol: 'http' | 'https';
  projectId: string;
  ingestUrl: string;
}

/**
 * A platform-specific adapter — each SDK package (sdk-browser, sdk-node, …) ships one. The core
 * client uses it to stamp events with the right SDK identity and to enrich them with
 * platform-only fields (browser request URL, Node runtime version, etc.) without core needing
 * to know about `window` or `process`.
 *
 * <p>{@code sdkVersion} is the version of the platform package the consumer installed (e.g.
 * {@code @arguslog/sdk-browser@1.1.0}), generated by each package's {@code gen-version.mjs}
 * from its own {@code package.json}. Distinct from sdk-core's {@code SDK_VERSION}, which
 * tracks the wire-format/protocol version — debugging an event we want to know which client
 * shipped it, not which core protocol it spoke.
 */
export interface PlatformAdapter {
  sdkName: string;
  sdkVersion: string;
  platform: Platform;
  enrichEvent?(event: EventPayload): void;
}

export interface StackParser {
  (stack: string | undefined): StackFrame[];
}
