#!/usr/bin/env node
/**
 * Build-time codegen — reads services/api/openapi.json and emits one MCP tool definition per
 * REST operation into src/generated/openapi-tools.ts. Tools are named
 * {@code arguslog_<group>_<op>} where {@code group} comes from the operation's first tag (or
 * the first path segment if the spec is untagged) and {@code op} is the operationId or a
 * normalized {@code <method>_<path>}. The generated module exports a single {@code OPENAPI_TOOLS}
 * array so the runtime side stays generic — adding endpoints to the API is a recompile away
 * from being callable by an LLM.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../../..');
const OPENAPI = resolve(ROOT, 'services/api/openapi.json');
const OUT_DIR = resolve(__dirname, '../src/generated');
const OUT_FILE = resolve(OUT_DIR, 'openapi-tools.ts');

const spec = JSON.parse(readFileSync(OPENAPI, 'utf8'));
const tools = [];
const seenNames = new Set();

for (const [path, ops] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(ops)) {
    if (!['get', 'post', 'put', 'patch', 'delete'].includes(method)) continue;
    if (!op || typeof op !== 'object') continue;

    const tag = (op.tags?.[0] ?? firstPathSegment(path) ?? 'misc').toLowerCase();
    const opId = op.operationId ?? `${method}_${path.replace(/[/{}-]+/g, '_').replace(/^_+|_+$/g, '')}`;
    let name = `arguslog_${normalize(tag)}_${normalize(opId)}`.replace(/_+/g, '_');
    // MCP tool names: lowercase, ≤64 chars, [a-z0-9_]. Trim if too long.
    if (name.length > 64) name = name.slice(0, 64).replace(/_+$/, '');
    // Disambiguate collisions by suffixing the method.
    if (seenNames.has(name)) name = `${name.slice(0, 60)}_${method}`.slice(0, 64);
    seenNames.add(name);

    const params = op.parameters ?? [];
    const pathParams = params.filter((p) => p.in === 'path');
    const queryParams = params.filter((p) => p.in === 'query');
    const hasBody = Boolean(op.requestBody);

    const summary = String(op.summary ?? op.description ?? `${method.toUpperCase()} ${path}`).split('\n')[0];
    const description =
      `${summary}\n\nMethod: ${method.toUpperCase()} ${path}` +
      (op.description && op.description !== op.summary ? `\n\n${op.description}` : '');

    tools.push({
      name,
      description,
      method: method.toUpperCase(),
      path,
      pathParams: pathParams.map((p) => ({ name: p.name, required: p.required ?? true, type: openApiTypeOf(p.schema) })),
      queryParams: queryParams.map((p) => ({ name: p.name, required: p.required ?? false, type: openApiTypeOf(p.schema) })),
      hasBody,
    });
  }
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT_FILE,
  `// Auto-generated by scripts/generate-tools.mjs from services/api/openapi.json.
// DO NOT EDIT BY HAND — re-run \`pnpm run generate\` after changing the OpenAPI spec.

export interface OpenApiToolParam {
  name: string;
  required: boolean;
  /** Coarse JSON Schema type — used to pick the right zod constructor at runtime. */
  type: 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object' | 'unknown';
}

export interface OpenApiTool {
  name: string;
  description: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  pathParams: OpenApiToolParam[];
  queryParams: OpenApiToolParam[];
  /** When true the tool also accepts a free-form \`body\` arg dispatched as the JSON request body. */
  hasBody: boolean;
}

export const OPENAPI_TOOLS: OpenApiTool[] = ${JSON.stringify(tools, null, 2)};
`,
  'utf8',
);

console.log(`✓ Generated ${tools.length} tools → ${OUT_FILE}`);

function firstPathSegment(path) {
  return path.split('/').filter(Boolean)[0] ?? null;
}

function normalize(s) {
  return String(s)
    .replace(/[A-Z]/g, (c) => '_' + c.toLowerCase())
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function openApiTypeOf(schema) {
  if (!schema || typeof schema !== 'object') return 'unknown';
  const t = schema.type;
  if (t === 'integer') return 'integer';
  if (t === 'number' || t === 'string' || t === 'boolean' || t === 'array' || t === 'object') return t;
  return 'unknown';
}
