#!/usr/bin/env node
// Mirrors sdk-core's gen-version: read package.json:version once and write
// src/version.generated.ts so the BrowserAdapter stamps the real SDK version on every
// event instead of a hardcoded literal that drifts with each npm release. Re-run via
// prebuild/pretest hooks so workspace consumers (apps/web, apps/landing) see live values.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const outPath = join(here, '..', 'src', 'version.generated.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
if (typeof pkg.version !== 'string' || !pkg.version) {
  console.error('[sdk-browser] missing or empty .version in package.json');
  process.exit(1);
}

const content =
  '// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand. Bump the version in\n' +
  '// package.json and rerun `pnpm build` (or any pretest/prebuild hook); the script reads\n' +
  '// package.json:version and rewrites this file before tsc compiles it.\n' +
  `export const SDK_VERSION = '${pkg.version}';\n`;

writeFileSync(outPath, content);
console.log(`[sdk-browser] wrote ${outPath} (version=${pkg.version})`);
